spring.application.name=jtx-api

# Logging
logging.level.root=INFO
logging.level.com.jtx.api=DEBUG
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n

